name: Deploy Flexiva to TriSys Site

on:
  workflow_dispatch:

jobs:
  deploy-customer:
    runs-on: ubuntu-latest
    
    steps:
    - name: Download Latest Obfuscated Code
      run: |
        git clone --single-branch --branch gh-pages https://github.com/TriSys-Business-Software/Flexiva.git .
        ls -la
        
    - name: Deploy to Customer GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        cname: flexiva.trisys.co.uk